# Generated by Django 5.2.6 on 2025-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_authuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='authuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
